#
# Helper module to parse the phidgets.json file generated by
# make_phidget_lists.py in the top level of thios project.
#
# This list scrapes the Phidget22 source code to extract the human
# readable descriptions of the serious devices & mode settings.
#


import json

class PhidgetInfo(object):
    def __init__(self, phidgetInfoFile=None):
        if phidgetInfoFile:
            # Read JSON with human-readable phidget sensors/modes/etc.
            with open(phidgetInfoFile, 'r', encoding="utf-8") as f:
                self.phidgetInfo = json.load(f)
        else:
            self.phidgetInfo = {}

    def getPhidgetTypeMenu(self, classes):
        # Example: myArray = [("option1", "First Option"),("option2","Second Option")]
        menu = []
        for phidget_class in classes:
            for item in self.phidgetInfo.get(phidget_class, {}):            
                menu.append( (item['value'], item['description']) )
        return sorted(menu, key=lambda x: (x[1][0].isdigit(), x[1]))

