#
# Helper module to parse the phidgets.json file generated by
# make_phidget_lists.py in the top level of thios project.
#
# This list scrapes the Phidget22 source code to extract the human
# readable descriptions of the serious devices & mode settings.
#


import json

Phidget_Units = {}
Phidget_Units['PHIDUNIT_NONE'] = ["none",""]
Phidget_Units['PHIDUNIT_BOOLEAN'] = ["boolean",""]
Phidget_Units['PHIDUNIT_PERCENT'] = ["percent","%"]
Phidget_Units['PHIDUNIT_DECIBEL'] = ["decibel","dB"]
Phidget_Units['PHIDUNIT_MILLIMETER'] = ["millimeter","mm"]
Phidget_Units['PHIDUNIT_CENTIMETER'] = ["centimeter","cm"]
Phidget_Units['PHIDUNIT_METER'] = ["meter","m"]
Phidget_Units['PHIDUNIT_GRAM'] = ["gram","g"]
Phidget_Units['PHIDUNIT_KILOGRAM'] = ["kilogram","kg"]
Phidget_Units['PHIDUNIT_MILLIAMPERE'] = ["milliampere","mA"]
Phidget_Units['PHIDUNIT_AMPERE'] = ["ampere","A"]
Phidget_Units['PHIDUNIT_KILOPASCAL'] = ["kilopascal","kPa"]
Phidget_Units['PHIDUNIT_VOLT'] = ["volt","V"]
Phidget_Units['PHIDUNIT_DEGREE_CELCIUS'] = ["degree Celsius","C"]
# Phidget_Units['PHIDUNIT_DEGREE_CELCIUS'] = ["degree Celsius","\xC2\xB0""C"]
Phidget_Units['PHIDUNIT_LUX'] = ["lux","lx"]
Phidget_Units['PHIDUNIT_GAUSS'] = ["gauss","G"]
Phidget_Units['PHIDUNIT_PH'] = ["pH",""]
Phidget_Units['PHIDUNIT_WATT'] = ["watt","W"]

stateName = {}
stateName['SENSOR_TYPE_1101_SHARP_2D120X'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_1101_SHARP_2Y0A02'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_1101_SHARP_2Y0A21'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_1102'] = Phidget_Units['PHIDUNIT_BOOLEAN']
stateName['SENSOR_TYPE_1103'] = Phidget_Units['PHIDUNIT_BOOLEAN']
stateName['SENSOR_TYPE_1104'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1105'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1106'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1107'] = Phidget_Units['PHIDUNIT_PERCENT']
stateName['SENSOR_TYPE_1108'] = Phidget_Units['PHIDUNIT_GAUSS']
stateName['SENSOR_TYPE_1109'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1110'] = Phidget_Units['PHIDUNIT_BOOLEAN']
stateName['SENSOR_TYPE_1111'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1112'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1113'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1114'] = Phidget_Units['PHIDUNIT_DEGREE_CELCIUS']
stateName['SENSOR_TYPE_1115'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1116'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1117'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_1118_AC'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_1118_DC'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_1119_AC'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_1119_DC'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_1120'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1121'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1122_AC'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_1122_DC'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_1123'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_1124'] = Phidget_Units['PHIDUNIT_DEGREE_CELCIUS']
stateName['SENSOR_TYPE_1125_HUMIDITY'] = Phidget_Units['PHIDUNIT_PERCENT']
stateName['SENSOR_TYPE_1125_TEMPERATURE'] = Phidget_Units['PHIDUNIT_DEGREE_CELCIUS']
stateName['SENSOR_TYPE_1126'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1127'] = Phidget_Units['PHIDUNIT_LUX']
stateName['SENSOR_TYPE_1128'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_1129'] = Phidget_Units['PHIDUNIT_BOOLEAN']
stateName['SENSOR_TYPE_1130_ORP'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_1130_PH'] = Phidget_Units['PHIDUNIT_PH']
stateName['SENSOR_TYPE_1131'] = Phidget_Units['PHIDUNIT_GRAM']
stateName['SENSOR_TYPE_1132'] = Phidget_Units['PHIDUNIT_MILLIAMPERE']
stateName['SENSOR_TYPE_1133'] = Phidget_Units['PHIDUNIT_DECIBEL']
stateName['SENSOR_TYPE_1134'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_1135'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_1136'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1137'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1138'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1139'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1140'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1141'] = Phidget_Units['PHIDUNIT_KILOPASCAL']
stateName['SENSOR_TYPE_1142'] = Phidget_Units['PHIDUNIT_LUX']
stateName['SENSOR_TYPE_1143'] = Phidget_Units['PHIDUNIT_LUX']
stateName['SENSOR_TYPE_1146'] = Phidget_Units['PHIDUNIT_MILLIMETER']
stateName['SENSOR_TYPE_3120'] = Phidget_Units['PHIDUNIT_KILOGRAM']
stateName['SENSOR_TYPE_3121'] = Phidget_Units['PHIDUNIT_KILOGRAM']
stateName['SENSOR_TYPE_3122'] = Phidget_Units['PHIDUNIT_KILOGRAM']
stateName['SENSOR_TYPE_3123'] = Phidget_Units['PHIDUNIT_KILOGRAM']
stateName['SENSOR_TYPE_3130'] = Phidget_Units['PHIDUNIT_PERCENT']
stateName['SENSOR_TYPE_3500'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3501'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3502'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3503'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3507'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_3508'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_3509'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_3510'] = Phidget_Units['PHIDUNIT_VOLT']
stateName['SENSOR_TYPE_3511'] = Phidget_Units['PHIDUNIT_MILLIAMPERE']
stateName['SENSOR_TYPE_3512'] = Phidget_Units['PHIDUNIT_MILLIAMPERE']
stateName['SENSOR_TYPE_3513'] = Phidget_Units['PHIDUNIT_MILLIAMPERE']
stateName['SENSOR_TYPE_3514'] = Phidget_Units['PHIDUNIT_WATT']
stateName['SENSOR_TYPE_3515'] = Phidget_Units['PHIDUNIT_WATT']
stateName['SENSOR_TYPE_3516'] = Phidget_Units['PHIDUNIT_WATT']
stateName['SENSOR_TYPE_3517'] = Phidget_Units['PHIDUNIT_WATT']
stateName['SENSOR_TYPE_3518'] = Phidget_Units['PHIDUNIT_WATT']
stateName['SENSOR_TYPE_3519'] = Phidget_Units['PHIDUNIT_WATT']
stateName['SENSOR_TYPE_3520'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_3521'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_3522'] = Phidget_Units['PHIDUNIT_CENTIMETER']
stateName['SENSOR_TYPE_3584'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3585'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3586'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3587'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3588'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_3589'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_MOT2002_HIGH'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_MOT2002_LOW'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_MOT2002_MED'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_VCP4114'] = Phidget_Units['PHIDUNIT_AMPERE']
stateName['SENSOR_TYPE_VOLTAGE'] = Phidget_Units['PHIDUNIT_NONE']
stateName['SENSOR_TYPE_VOLTAGERATIO'] = Phidget_Units['PHIDUNIT_NONE']

class PhidgetInfo(object):
    def __init__(self, phidgetInfoFile=None):
        if phidgetInfoFile:
            # Read JSON with human-readable phidget sensors/modes/etc.
            with open(phidgetInfoFile, 'r') as f:
                self.phidgetInfo = json.load(f)
        else:
            self.phidgetInfo = {}

    def getPhidgetTypeMenu(self, classes):
        # Example: myArray = [("option1", "First Option"),("option2","Second Option")]
        menu = []
        for phidget_class in classes:
            for item in self.phidgetInfo.get(phidget_class, {}):            
                menu.append( (item['value'], item['description']) )
        return sorted(menu, key=lambda x: (x[1][0].isdigit(), x[1]))
        

